### PR TITLE
Adds frame seeking hotkeys

### PR DESCRIPTION
**Pull request by DavidXenakis**
Also, refactor the method for finding the right timestamp to start/end at when a trim exists. The new method uses a binary search, so it should be more efficient than a linear seek. I use this method to wrap around in the frame seeking.

Tested using trimmed videos at different speeds, and everything works as expected.

Updated Readme with new hotkeys

### CODE REVIEW

**Comment by DavidXenakis** [comment]
Do not merge yet, I just found a edge case where the playback doesn't work correctly when playing backwards

**Comment by DavidXenakis** [comment]
@exeldro Could you please take a look? This is a killer feature for my use-case!

**Comment by exeldro** [comment]
At first glance it looks good. I plan on taking a good look this week.

**Review by exeldro — CHANGES_REQUESTED** [review]

**Comment by DavidXenakis** [comment]
With my latest changes, I've addressed your comments, added localization text, and added a feature to allow a coarse grained frame step, which defaults to 5 frames. This allows me to, for instance, hold shift when stepping frames to step a larger amount.

**Comment by exeldro** [comment]
I will do some fixes on master

**Pull request merged**
